### ISSUE TITLE
no such file dlib/opencv.h

### ISSUE THREAD

**Issue by PierreHao** [mitmul/dlibss#1]
When make, dlib/opencv.h no such file. It means my dlib doesn't install successfully? How can I do with dlib? I have done as follows:
mkdir build; cd build; cmake .. ; cmake --build .

**Comment by mitmul** [comment]
This is a wrapper of find_candidate_object_locations function in dlib, but its python wrapper is officially released already.
http://dlib.net/find_candidate_object_locations.py.html

So you don't need to use these codes. Please check out the official python APIs.

**Comment by PierreHao** [comment]
It means i don't need to use dlibss? After installing dlib, i can use python api directly?

**Comment by mitmul** [comment]
Yes, you don't need to use dlibss. Just install dlib itself only, and you can use the python api.

**Comment by PierreHao** [comment]
Firstly, thank you very much for your reply
I have downloaded from https://github.com/davisking/dlib 
and then cd dlib/dlib
mkdir build
cd build
cmake ..
make -j4
all run successfully
But when i use import dlib, it couldn't find dlib, what's wrong?

**Comment by mitmul** [comment]
When you use cmake, modify properties and link python related files correctly.
If further problems happen, please ask about it in the forum:
http://sourceforge.net/p/dclib/discussion/

**Comment by PierreHao** [comment]
Ok, thank you. Is dlib.find_candidate_object_locations same as selective search?
